Fliplet/fliplet-widget-google-submission

interface.html
js/interface.js

- Added Version Number
- Fixed issue with Splash Screen
- Error message if icon isn't 1024x1024

Added Version Number and Version Code

---

js/interface.js

previous results should be updated on save and with the first completed submission

previous results should be updated on save

---

interface.html
js/interface.js

- Added support to open the File Manager in an overlay in the Screenshots section

Open file manager

---

interface.html

Ref. https://github.com/Fliplet/fliplet-studio/issues/2372

Removed app icon name input limit

---

interface.html
js/interface.js

for https://github.com/Fliplet/fliplet-android-version-2/pull/64

support for firebase project id

---

js/interface.js

Ref. Fliplet/fliplet-studio#3611 (comment)

Disabled save button upon save

---

css/interface.css
js/interface.js

Ref.
- https://github.com/Fliplet/fliplet-studio/issues/3860
- https://github.com/Fliplet/fliplet-studio/issues/3861
- https://github.com/Fliplet/fliplet-studio/issues/3862
- https://github.com/Fliplet/fliplet-studio/issues/3863

Fixes issues where AAB interface isn't loaded correctly in Safari

---

interface.html

ref https://github.com/Fliplet/fliplet-studio/issues/2867

typo in push notification

---

js/interface.js

https://github.com/Fliplet/fliplet-studio/issues/3755
Created a save function witch is saving data on change icon or splash screen.
Slightly altered saving functions so that they return a promise.

Saving form information when user go to another modal

---

interface.html

https://github.com/Fliplet/fliplet-studio/issues/4965
Corrected text in new tabs.

Corrected text in new tabs.

---

interface.html

https://github.com/Fliplet/fliplet-studio/issues/4965
Added bracket in the text

Added bracket in the text

---

interface.html

https://github.com/Fliplet/fliplet-studio/issues/4965
Updated capitalization of the firebase tab.

Updated capitalization of the firebase tab.

---

js/interface.js

Fliplet/fliplet-studio#5098
Checking if firebase was connected

Checking if firebase was connected

---

js/interface.js

https://github.com/Fliplet/fliplet-studio/issues/5098
Show correct message when firebase is enabled on Signed APK tab

Show correct message when firebase is enabled on Signed APK tab

---

interface.html

@sofiiakvasnevska
Fliplet/fliplet-studio#5531
Added links to articles provided by Brett.

Help links now lead to correct articles about analytics

---

js/interface.js

Requires https://github.com/Fliplet/fliplet-studio/pull/6331

[Feature] Track app launch events via Studio

---

interface.html

Ref. https://weboo.atlassian.net/browse/ID-840

ID-840 [Feat] Adds admin labels

---

.eslintrc
.gitignore
js/interface.js
package-lock.json
package.json

Ref. Fliplet/fliplet-studio#6940 https://weboo.atlassian.net/browse/ID-1346

ID-1346 [Feat] Ensure app submission requests are blocked if ToS needs review

---

css/interface.css
interface.html
js/interface.js
js/interface.templates.js

- Added limits based on app plan

[Feat] Added limits based on app plan

---

js/interface.js

- Fire event when opening billing section

[Maintenance] Fire event when opening billing section

---

js/interface.js

https://weboo.atlassian.net/browse/GD-384
- Fixes an issue that prevented users to save their progress and would open the billing section instead.

GD-384 [Fix] Allow to save progress

---

interface.html

@romanyosyfiv
OD-600 https://weboo.atlassian.net/browse/OD-600
Added Bundle ID validation. The user will not be able to submit the form if the Bundle ID is in the wrong format.

OD-600 [Feature] Added Bundle ID validation

---

interface.html
js/interface.js

@romanyosyfiv
OD-596 https://weboo.atlassian.net/browse/OD-596
Added app version number validation. The user will not be able to submit the form if the version number is in the wrong format or is less than a pre-existing version number and version code.

OD-596 [Feature] Added app version number validation

---

css/interface.css
interface.html
js/interface.js

@romanyosyfiv
OD-599 https://weboo.atlassian.net/browse/OD-599
Added app icon, splash screen, scrennshots validation. The user will not be able to submit the form if the app icon, splash screen, scrennshots have not been added.

OD-599 [Feature] Added app icon, splash screen, scrennshots validation

---

interface.html

@romanyosyfiv @inna-bieshulia 
OD-727 https://weboo.atlassian.net/browse/OD-727
A typo has been fixed, and the link has been replaced with a new one.

OD-727 [Fix] Fix broken link and typo

---

interface.html

@romanyosyfiv @inna-bieshulia
OD-755 https://weboo.atlassian.net/browse/OD-755
The link has been replaced with a new one.

OD-755 [Fix] Fix broken link

---

js/interface.js

Ref. https://weboo.atlassian.net/browse/ID-2119

ID-2119 [Fix] Correctly check for app version numbers

---

js/interface.js

Ref. https://weboo.atlassian.net/browse/ID-2119

ID-2119 [Fix] Allow the same version number be used until it's submitted for build

---

js/interface.js

Google submission ->  APK/IPK files rendering URL
This PR will ensure that the submission's APK/IPK files do not have a token on rendering 
[XOR-574](https://weboo.atlassian.net/browse/XOR-574)
Add any relevant sample input/output, screenshots or screen recordings.
https://user-images.githubusercontent.com/101858104/194862192-f1163696-2dd2-4797-ab03-42f45691927a.mp4

XOR-574 [FEAT] Ensure submission's APK/IPK files do not have a token on rendering 

---

interface.html
js/interface.js

Ref. https://weboo.atlassian.net/browse/ID-3598

ID-3598 [Feat] Add version code and number to build summary

---

css/interface.css
interface.html
js/gcmValidation.js
widget.json

https://weboo.atlassian.net/browse/ID-4319
New demo video with mapped messages, and with testing instructions:
https://github.com/Fliplet/fliplet-widget-google-submission/assets/144125903/662dbaea-7fce-49fa-8dbc-c908042c3750
Here's the way of testing 200 responses with different error:

ID-4319 [feat] gcm server key test button

---

js/schemaValidation.js

https://weboo.atlassian.net/browse/ID-4515

ID-4515 [fix] schema validation for handling undefined required and properties
